/*
 * Copyright (c) FOREVER, Jefferson Buot. All rights reserved.
 * Build | Imagine | Think | Explore -> By: Jeff 
 */
package artemis.dialogs;

import java.sql.Connection;

/**
 *
 * @author Jefferson
 */
public class InstituteStatistics extends javax.swing.JDialog {

    private Connection con;

    /**
     * Creates new form InstituteStatistics
     */
    public InstituteStatistics() {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
    }

    public static void showDialog(Connection con) {
        new InstituteStatistics().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbActive = new com.alee.laf.checkbox.WebCheckBox();
        cbPublished = new com.alee.laf.checkbox.WebCheckBox();
        cbDraft = new com.alee.laf.checkbox.WebCheckBox();
        panel = new com.alee.laf.panel.WebPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Institute Statistics");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Access Type", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N

        cbActive.setSelected(true);
        cbActive.setText("Active");
        cbActive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActiveActionPerformed(evt);
            }
        });
        jPanel1.add(cbActive);

        cbPublished.setText("Published");
        cbPublished.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbPublished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPublishedActionPerformed(evt);
            }
        });
        jPanel1.add(cbPublished);

        cbDraft.setText("Draft");
        cbDraft.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDraftActionPerformed(evt);
            }
        });
        jPanel1.add(cbDraft);

        panel.setUndecorated(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 231, Short.MAX_VALUE))
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActiveActionPerformed
        if (!cbPublished.isSelected() && !cbDraft.isSelected()) {
            cbActive.setSelected(true);
        }
    }//GEN-LAST:event_cbActiveActionPerformed

    private void cbPublishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPublishedActionPerformed
        if (!cbActive.isSelected() && !cbDraft.isSelected()) {
            cbPublished.setSelected(true);
        }
    }//GEN-LAST:event_cbPublishedActionPerformed

    private void cbDraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDraftActionPerformed
        if (!cbActive.isSelected() && !cbPublished.isSelected()) {
            cbDraft.setSelected(true);
        }
    }//GEN-LAST:event_cbDraftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.checkbox.WebCheckBox cbActive;
    private com.alee.laf.checkbox.WebCheckBox cbDraft;
    private com.alee.laf.checkbox.WebCheckBox cbPublished;
    private javax.swing.JPanel jPanel1;
    private com.alee.laf.panel.WebPanel panel;
    // End of variables declaration//GEN-END:variables
}
