/*
 * Copyright (c) FOREVER, Jefferson Buot. All rights reserved.
 * Build | Imagine | Think | Explore -> By: Jeff 
 */
package artemis.server_module;

import artemis.classes.IconFactory;
import artemis.classes.NetCon;
import artemis.dialogs.ArtemisMessage;
import artemis.dialogs.ArtemisPrompt;
import com.alee.extended.window.WebPopOver;
import com.alee.laf.panel.WebPanel;
import com.alee.managers.hotkey.ButtonHotkeyRunnable;
import com.alee.managers.hotkey.Hotkey;
import com.alee.managers.hotkey.HotkeyManager;
import com.alee.managers.language.data.TooltipWay;
import com.alee.managers.tooltip.TooltipManager;
import com.alee.utils.FileUtils;
import com.jeff.util.ChromieDB;
import com.jeff.util.Cipher;
import java.awt.Component;
import java.awt.Toolkit;
import java.io.File;
import java.net.Socket;
import javax.swing.ImageIcon;

/**
 *
 * @author Jefferson
 */
public class AdminLogin extends WebPanel {

    /**
     * Creates new form Login
     */
    WebPopOver popOver;

    NetCon nc;
    Socket socket;
    boolean ok = false;
    AdminAccount account;
    ArtemisPrompt load;
    ImageIcon infoIcon = new ImageIcon(getClass().getResource("/artemis/img/Message-Warning.png"));

    public AdminLogin(WebPopOver popOver) {
        this.popOver = popOver;
        initComponents();
        initFile();
        setUndecorated(false);
        setShadeWidth(0);
        HotkeyManager.registerHotkey(this, btnSubmit, Hotkey.ENTER, new ButtonHotkeyRunnable(btnSubmit, 50), TooltipWay.trailing);
    }

    private void initFile() {
        File file = new File(FileUtils.getUserHomePath() + "acdb.acc");
        if (!file.exists()) {
            AdminAccount acc = new AdminAccount(Cipher.encrypt("admin"), Cipher.encrypt("artemisadmin"));
            ChromieDB.saveData(file, acc);
        }
        account = (AdminAccount) ChromieDB.loadData(file, AdminAccount.class);
    }

    public static boolean showDialog(Component comp) {
        WebPopOver view = new WebPopOver(comp);
        view.setCloseOnFocusLoss(false);
        view.setModal(true);
        view.setMargin(0);
        AdminLogin log = new AdminLogin(view);
        view.add(log);
        //Center
        int x = Toolkit.getDefaultToolkit().getScreenSize().width / 2 - (int) view.getPreferredSize().getWidth() / 2;
        int y = Toolkit.getDefaultToolkit().getScreenSize().height / 2 - (int) view.getPreferredSize().getHeight() / 2;
        System.out.println(view.getPreferredSize().getWidth());
        view.show(x, y);
        return log.isOk();
    }

    public boolean isOk() {
        return ok;
    }

    private void submit() {
        String un = txtUsername.getText().trim().toLowerCase();
        String pw = txtPassword.getText().trim();
        if (un.isEmpty()) {
            TooltipManager.showOneTimeTooltip(txtUsername, null, IconFactory.infoIcon,
                    "Please enter your username.");
            return;
        }
        if (pw.isEmpty()) {
            TooltipManager.showOneTimeTooltip(txtPassword, null, IconFactory.infoIcon,
                    "Please enter your password.");
            return;
        }
        if (Cipher.decrypt(account.getPassword()).equals(pw) && Cipher.decrypt(account.getUsername()).equals(un)) {
            ok = true;
            popOver.dispose();
        } else {
            ArtemisMessage.showDialog(popOver, "Wrong username/password.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        webButton1 = new com.alee.laf.button.WebButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new com.alee.laf.text.WebTextField();
        txtPassword = new com.alee.laf.text.WebPasswordField();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(81, 81, 81));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("   Artemis Administrator Access");

        webButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artemis/img/exit.png"))); // NOI18N
        webButton1.setUndecorated(true);
        webButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 4, Short.MAX_VALUE))
            .addComponent(webButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artemis/img/blahblahuser.png"))); // NOI18N

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUsername.setHideInputPromptOnFocus(false);
        txtUsername.setInputPrompt("Username");
        txtUsername.setRound(8);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPassword.setHideInputPromptOnFocus(false);
        txtPassword.setInputPrompt("Password");
        txtPassword.setRound(8);

        btnSubmit.setBackground(new java.awt.Color(51, 51, 51));
        btnSubmit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artemis/img/login.png"))); // NOI18N
        btnSubmit.setText("Login");
        btnSubmit.setHideActionText(true);
        btnSubmit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void webButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1ActionPerformed
        popOver.dispose();
        System.exit(0);
    }//GEN-LAST:event_webButton1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        submit();
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.alee.laf.text.WebPasswordField txtPassword;
    private com.alee.laf.text.WebTextField txtUsername;
    private com.alee.laf.button.WebButton webButton1;
    // End of variables declaration//GEN-END:variables
}
