/*
 * Copyright (c) FOREVER, Jefferson Buot. All rights reserved.
 * Build | Imagine | Think | Explore -> By: Jeff 
 */
package artemis;

import artemis.classes.ArtemisStatistics;
import artemis.dialogs.ArtemisPrompt;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.chart.XYChart;

/**
 *
 * @author Jefferson
 */
public class GraphReport extends javax.swing.JDialog {

    ArtemisPrompt load;

    /**
     * Creates new form GraphReport
     *
     * @param series1
     * @param series2
     */
    public GraphReport(XYChart.Series series1, XYChart.Series series2) {
        initComponents();
        load = new ArtemisPrompt(this, "Rendering graph...");
        panel.add(new JFXPanel() {
            {
                Platform.runLater(() -> {
                    load.showDialog();
                    setScene(ArtemisStatistics.getScene(series1, series2));
                    load.closeDialog();
                });
            }
        });
        setLocationRelativeTo(null);
        setModal(true);
    }

    public static void showDialog(XYChart.Series series1, XYChart.Series series2) {
        new GraphReport(series1, series2).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBackground(new java.awt.Color(102, 102, 102));
        panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
